- name: Set locale in cloud.cfg
  lineinfile: 
    dest: /etc/cloud/cloud.cfg 
    line: "locale: {{ locale }}"
    state: present
  when: isDocker == "no"

- name: Set repo_upgrade in cloud.cfg
  lineinfile: 
    dest: /etc/cloud/cloud.cfg 
    regexp: "repo_upgrade:" 
    line: "repo_upgrade: {{ aws_repo_upgrade }}"
    state: present
  when: isDocker == "no"