- name: Install utilities
  yum: name={{item}} state=latest
  with_items:
  - "wget"
  - "tcpdump"
  - "sysstat"
  - "nmap"
  - "gcc"
  - "make"
  - "git"
  - "subversion"
  - "openssl-devel"
  - "vim-enhanced"
  - "python-devel"
  - "python-setuptools"
  - "python-pip"
  - "curl"
  - "curl-devel"
  - "zip"
  - "unzip"
- name: Install MySQL-Python for Amazon Linux
  yum: name="MySQL-python" state=latest
  when: aws_awslinux in ["1","2"]
- name: Install mail
  yum: name="mail" state=latest
  when: centos_version=="6"
- name: Install mailx
  yum: name="mailx" state=latest
  when: centos_version=="7"
