- name: Install Fedora EPEL repository
  yum:
    name:
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: Install Amazon Linux Extra EPEL repository
  shell: amazon-linux-extras enable epel -y

- name: "Install Amazon Linux Extra Nginx for Amazon Linux 2"
  shell: amazon-linux-extras enable nginx1 -y
  when:
    - webserver_handle=="nginx"

- name: "Install Amazon Linux Extra {{php_version_amznlinux2}} for Amazon Linux 2"
  shell: amazon-linux-extras enable {{ php_version_amznlinux2 }} -y
  when:
    - php_version_amznlinux2 not in ["php56", "php81"]

- name: Install Remi repository for Amazon Linux 2 PHP5.6 and PHP8.1
  yum:
    name:
      - https://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present
  when: php_version_amznlinux2 in ["php56","php81"]

- name: Disable remi-safe repo (ARM is not yet available)
  ini_file:
    dest: /etc/yum.repos.d/remi-safe.repo
    section: remi-safe
    option: enabled
    value: 0
  when: php_version_amznlinux2 in ["php56","php81"]

- name: Install utilities
  yum:
    name:
      - "aws-cfn-bootstrap"
      - "cloud-init"
      - "aws-cli"
    state: latest
