- name: Install utilities
  yum: name={{item}} state=latest
  with_items:
  - "telnet"
  - "wget"
  - "tcpdump"
  - "sysstat"
  - "nmap"
  - "gcc"
  - "make"
  - "git"
  - "subversion"
  - "openssl-devel"
  - "vim-enhanced"
  - "python-devel"
  - "python-setuptools"
  - "curl"
  - "curl-devel"
- name: Install MySQL-Python for Amazon Linux
  yum: name={{item}} state=latest
  when: aws_awslinux in ["1","2"]
  with_items:
  - "MySQL-python"
- name: Install mail
  yum: name={{item}} state=latest
  when: centos_version=="6"
  with_items:
  - "mail"
- name: Install mailx
  yum: name={{item}} state=latest
  when: centos_version=="7"
  with_items:
  - "mailx"
