- name: Install epel repository
  yum:
    name:
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
    state: present

- name: Install remi repository
  yum:
    name:
      - http://rpms.remirepo.net/enterprise/remi-release-6.rpm
    state: present
  when: centos_phprepo=="remi"

#- name: Remove repository (and clean up left-over metadata)
#  yum_repository:
#    name: remi
#    state: absent
