- name: Install epel repository
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present
  when: aws_awslinux!="2"

- name: "Install Amazon Linux Extra Epel, {{php_version_amznlinux2}} and Nginx 1.12 for Amazon Linux 2"
  shell: amazon-linux-extras install epel {{ php_version_amznlinux2 }} nginx1.12 -y
  when: aws_awslinux=="2"

- name: Install utilities
  yum: name={{item}} state=latest
  with_items:
  - "aws-cfn-bootstrap"
  - "cloud-init"
  - "aws-cli"
