- name: Install extra packages (yum)
  yum:
    name:
      - "git"  # etckeeper requires git
      - "etckeeper"
      #  - "monit"
    # enablerepo: epel
  when: aws_awslinux != "2023"

- name: Install extra packages (dnf for AL2023)
  dnf:
    name:
      - "git"  # etckeeper requires git
      - "etckeeper"
      #  - "monit"
  when: aws_awslinux == "2023"
