- name: Install Fedora EPEL repository
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: Enable EPEL in Amazon Linux Extras
  command: amazon-linux-extras enable epel
  args:
    creates: /etc/yum.repos.d/epel.repo

- name: Enable Nginx1 in Amazon Linux Extras for Amazon Linux 2
  command: amazon-linux-extras enable nginx1
  args:
    creates: /etc/yum.repos.d/nginx1.repo
  when: webserver_handle == "nginx"

- name: Enable Amazon Linux Extra for PHP version
  command: amazon-linux-extras enable {{ php_version_amznlinux2 }}
  args:
    creates: "/etc/yum.repos.d/{{ php_version_amznlinux2 }}.repo"
  when: php_version_amznlinux2 not in ["php56", "php80", "php81"]

- name: Install Remi repo for legacy PHP versions
  yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present
  when: php_version_amznlinux2 in ["php56", "php80", "php81"]

- name: Disable remi-safe repo (ARM not available)
  ini_file:
    dest: /etc/yum.repos.d/remi-safe.repo
    section: remi-safe
    option: enabled
    value: 0
  when: php_version_amznlinux2 in ["php56", "php80", "php81"]

- name: Install common utilities
  yum:
    name:
      - aws-cfn-bootstrap
      - cloud-init
      - aws-cli
    state: latest