- name: Install MySQL Server for Amazon Linux
  yum:
    name:
      -  mysql{{mysql_repo}}-server
    state: latest
  when: aws_awslinux =="1"
  register: mysqlresult

- name: Install MySQL Server for Amazon Linux 2
  yum:
    name:
      -  mysql-community-server
    state: latest
  when: aws_awslinux =="2"
  register: mysqlresult

- name: Install MySQL Server for CentOS
  yum:
    name:
      - mysql-community-server
    enablerepo: mysql{{mysql_repo}}-community
    state: latest
  when: aws_awslinux =="no"
  register: mysqlresult

- name: Start mysqld (CentOS6)
  service: name=mysqld state=started enabled=yes
  when:
    - centos_version=="6"
    - isDocker=="no"
- name: Start mysqld (CentOS7)
  when:
    - centos_version=="7"
    - isDocker=="no"
  systemd: name=mysqld state=started enabled=yes

- include_tasks: set_mysqlroot.yml
  when: isDocker=="no"

- name: Replace MySQL Config to disable performance schema
  template: src=my.conf.j2 dest=/etc/my.conf
  notify: Restart mysqld