- name: Install MySQL Server for Amazon Linux
  yum: state=latest
  when: aws_awslinux =="1"
  name: ['mysql{{mysql_repo}}-server']
  register: mysqlresult

## Amazon Linux 2 is not supported yet

- name: Install MySQL Server for CentOS
  yum: name={{item}} enablerepo=mysql{{mysql_repo}}-community state=latest
  when: aws_awslinux =="no"
  with_items:
  - mysql-community-server
  register: mysqlresult

- name: Start mysqld (CentOS6)
  when: centos_version=="6"
  service: name=mysqld state=started enabled=yes
- name: Start mysqld (CentOS7)
  when: centos_version=="7"
  systemd: name=mysqld state=started enabled=yes

- include: set_mysqlroot.yml

- name: Replace MySQL Config to disable performance schema
  template: src=my.conf.j2 dest=/etc/my.conf
  notify: Restart mysqld