- name: Install mysql
  yum: name={{item}} state=latest
  with_items:
  - mysql56-server
  register: result
- name: Start mysqld (CentOS6)
  when: centos_version=="6"
  service: name=mysqld state=started enabled=yes
- name: Start mysqld (CentOS7)
  when: centos_version=="7"
  systemd: name=mysqld state=started enabled=yes

- include: set_mysqlroot.yml

- name: Replace MySQL Config to disable performance schema
  template: src=vhost_default.conf.j2 dest=/etc/my.conf
  notify: Restart MySQL
