- name: Chenge Directory Permission (files) - Same as SSH User
  file: path="{{vhost_docroot}}{{vhost_domain}}/application/files/" state=directory recurse=yes owner={{c5dir_user}} group={{c5dir_group}} mode=0775
  when:
    - result.stat.exists == False
    - webserver_changeowner == "yes"
- name: Chenge Directory Permission (config) - Same as SSH User
  file: path="{{vhost_docroot}}{{vhost_domain}}/application/config/" state=directory recurse=yes owner={{c5dir_user}} group={{c5dir_group}} mode=0775
  when:
    - result.stat.exists == False
    - webserver_changeowner == "yes"
- name: Chenge Directory Permission (packagess) - Same as SSH User
  file: path="{{vhost_docroot}}{{vhost_domain}}/application/packages/" state=directory recurse=yes owner={{c5dir_user}} group={{c5dir_group}} mode=0775
  when:
    - result.stat.exists == False
    - webserver_changeowner == "yes"

- name: Chenge Directory Permission (files)  - {{webserver_handle}} User
  file: path="{{vhost_docroot}}{{vhost_domain}}/application/files/" state=directory recurse=yes owner={{webserver_handle}} group={{webserver_handle}} mode=0775
  when:
    - result.stat.exists == False
    - webserver_changeowner == "no"
- name: Chenge Directory Permission (config)  - {{webserver_handle}} User
  file: path="{{vhost_docroot}}{{vhost_domain}}/application/config/" state=directory recurse=yes owner={{webserver_handle}} group={{webserver_handle}} mode=0775
  when:
    - result.stat.exists == False
    - webserver_changeowner == "no"
- name: Chenge Directory Permission (packages) - {{webserver_handle}} User
  file: path="{{vhost_docroot}}{{vhost_domain}}/application/packages/" state=directory recurse=yes owner={{webserver_handle}} group={{webserver_handle}} mode=0775
  when:
    - result.stat.exists == False
    - webserver_changeowner == "no"

