- name: Check concrete5 Installed
  stat: path={{vhost_docroot}}{{vhost_domain}}/application/config/database.php
  register: result

#- name: include Vars Apache
#  include_vars: vars_apache.yml
#  when: webserver_handle=="apache"

#- name: include Vars Nginx
#  include_vars: vars_nginx.yml
#  when: webserver_handle=="nginx"

- include: 10_upload_concrete5.yml
- include: 20_install_concrete5.yml
  when: c5_installation=="yes"
- include: 25_directory_permission.yml
- include: 30_upload_concrete5_config.yml
- include: 40_restart_nginx.yml
  when: webserver_handle=="nginx"
- include: 40_restart_apache.yml
  when: webserver_handle=="apache"
