- name: Check concrete5 Installed
  stat: path={{vhost_docroot}}{{vhost_domain}}/application/config/database.php
  register: result

#- name: include Vars Apache
#  include_vars: vars_apache.yml
#  when: webserver_handle=="apache"

#- name: include Vars Nginx
#  include_vars: vars_nginx.yml
#  when: webserver_handle=="nginx"

- include_tasks: 10_upload_concrete5.yml
  when: c5_upload=="yes"
- include_tasks: 20_install_concrete5.yml
  when: c5_installation=="yes"
- include_tasks: 25_directory_permission.yml
- include_tasks: 30_upload_concrete5_config.yml
- include_tasks: 40_restart_nginx.yml
  when:
    - webserver_handle=="nginx"
    - isDocker=="no"
- include_tasks: 40_restart_apache.yml
  when:
    - webserver_handle=="apache"
    - isDocker=="no"
