- name: Remove MariaDB lib
  yum: name=mariadb-lib state=absent

- name: Install MySQL Repo for CentOS {{centos_version}}
  yum: name=http://dev.mysql.com/get/mysql{{mysql_repo}}-community-release-el{{centos_version}}-7.noarch.rpm  state=present