- name: Install Nginx and PHP for Amazon Linux
  when: aws_awslinux=="yes"
  yum: name={{ item }} state=latest
  with_items:
  - "nginx"
  - "php70"
  - "php70-devel"
  - "php70-cli"
  - "php70-gd"
  - "php70-mbstring"
  - "php70-pecl-memcached"
  - "php70-mysqlnd"
  - "php70-xml"
  - "php70-opcache"
  - "php70-mcrypt"
  - "php70-fpm"
  - "php70-zip"
  - "jq"

- name: Install Nginx and PHP for CentOS
  when: aws_awslinux!="yes"
  yum: name={{ item }} state=latest
  with_items:
  - "nginx"
  - "php71w"
  - "php71w-common"
  - "php71w-cli"
  - "php71w-devel"
  - "php71w-fpm"
  - "php71w-gd"
  - "php71w-intl"
  - "php71w-pecl-imagick"
  - "php71w-pdo"
  - "php71w-pecl-memcached"
  - "php71w-mbstring"
  - "php71w-mcrypt"
  - "php71w-mysqlnd"
  - "php71w-opcache"
  - "php71w-soap"
  - "php71w-xml"
  - "jq"

- name: Add User to Nginx-group
  user: name={{ item }} groups=nginx state=present
  with_items: "{{ add_users }}"

- name: Add Nginx to User-group
  user: name=nginx groups={{ item }} state=present
  with_items: "{{ add_users }}"

- include: set_php-fpm.yml
- include: set_php.yml
- include: set_nginx.yml
- include: set_nginx-vhost.yml

- name: Start Nginx
  service: name=nginx state=started enabled=yes
- name: Start php-fpm
  service: name=php-fpm state=started enabled=yes

