- name: Install Nginx and PHP for Amazon Linux 1
  when: aws_awslinux=="1"
  yum: name={{ item }} state=latest
  with_items:
  - "nginx"
  - "php71"
  - "php71-common"
  - "php71-cli"
  - "php71-devel"
  - "php71-fpm"
  - "php71-gd"
  - "php71-intl"
  - "php71-mbstring"
  - "php71-mysqlnd"
  - "php71-mcrypt"
  - "php71-opcache"
  - "php71-pdo"
  - "php71-pecl-imagick"
  - "php71-pecl-memcached"
  - "php71-xml"
  - "jq"

- name: Install Nginx and PHP for Amazon Linux 2
  when: aws_awslinux=="2"
  yum: name={{item}} state=latest
  with_items:
  - "php-devel"
  - "php-gd"
  - "php-intl"
  - "php-mbstring"
  - "php-opcache"
#  - "php-pecl-memcache"
  - "php-xml"
#  - "nginx"
#  - "php"
#  - "php-common"
#  - "php-cli"
#  - "php-fpm"
#  - "php-mysqlnd"
#  - "php-pdo"
#  - "php-mcrypt"  (N/A)
#  - "php-pecl-imagick" (N/A)

- name: Install Nginx and PHP for CentOS
  when: aws_awslinux=="no"
  yum: name={{ item }} state=latest
  with_items:
  - "nginx"
  - "php71w"
  - "php71w-common"
  - "php71w-cli"
  - "php71w-devel"
  - "php71w-fpm"
  - "php71w-gd"
  - "php71w-intl"
  - "php71w-pdo"
  - "php71w-pecl-imagick"
  - "php71w-pecl-memcached"
  - "php71w-mbstring"
  - "php71w-mcrypt"
  - "php71w-mysqlnd"
  - "php71w-opcache"
  - "php71w-soap"
  - "php71w-xml"
  - "jq"

- name: Add User to Nginx-group
  user: name={{ item }} groups=nginx state=present
  with_items: "{{ add_users }}"

- name: Add Nginx to User-group
  user: name=nginx groups={{ item }} state=present
  with_items: "{{ add_users }}"

- include: set_php-fpm.yml
- include: set_php.yml
- include: set_nginx.yml
- include: set_nginx-vhost.yml

- name: Start Nginx
  when: centos_version=="6"
  service: name=nginx state=started enabled=yes
- name: Start php-fpm
  when: centos_version=="6"
  service: name=php-fpm state=started enabled=yes

- name: Start Nginx
  when: centos_version=="7"
  systemd: name=nginx state=started enabled=yes
- name: Start php-fpm
  when: centos_version=="7"
  systemd: name=php-fpm state=started enabled=yes
