- name: Install Nginx
  yum:
    name:
      - "nginx"
    state: latest

- name: Add User to Nginx-group
  user: name={{ item }} groups=nginx state=present
  with_items: "{{ add_users }}"

- name: Add Nginx to User-group
  user: name=nginx groups={{ item }} state=present
  with_items: "{{ add_users }}"

- name: Start Nginx
  when:
    - centos_version=="6"
    - NginxPHPResult.changed == True
    - isDocker=="no"
  service: name=nginx state=started enabled=yes
- name: Start Nginx
  systemd: name=nginx state=started enabled=yes
  when:
    - centos_version=="7"
    - NginxPHPResult.changed == True
    - isDocker=="no"
- include: set_nginx.yml
- include: set_nginx-vhost.yml

- name: Chenge Directory Permission -  Nginx Log
  file: path="/var/log/nginx/" state=directory recurse=yes mode=0755
