- name: Install Nginx and PHP for Amazon Linux 1
  when: aws_awslinux=="1"
  yum: name={{ item }} state=latest
  with_items:
  - "nginx"
  - "{{php_version_yum}}"
  - "{{php_version_yum}}-common"
  - "{{php_version_yum}}-cli"
  - "{{php_version_yum}}-devel"
  - "{{php_version_yum}}-fpm"
  - "{{php_version_yum}}-gd"
  - "{{php_version_yum}}-intl"
  - "{{php_version_yum}}-mbstring"
  - "{{php_version_yum}}-mysqlnd"
  - "{{php_version_yum}}-opcache"
  - "{{php_version_yum}}-pdo"
  - "{{php_version_yum}}-pecl-imagick"
  - "{{php_version_yum}}-pecl-memcached"
  - "{{php_version_yum}}-pecl-redis"
  - "{{php_version_yum}}-xml"
  - "jq"
- name: Install PHP mcrypt extension for Amazon Linux
  when:
    - aws_awslinux=="1"
    - php_version_yum !="php72"
  yum: name={{item}} state=latest
  with_items:
  - "{{php_version_yum}}-mcrypt"

- name: Install Nginx and PHP for Amazon Linux 2
  when: aws_awslinux=="2"
  yum: name={{item}} state=latest
  with_items:
  - "php-devel"
  - "php-gd"
  - "php-intl"
  - "php-mbstring"
  - "php-opcache"
#  - "php-pecl-memcache"
  - "php-xml"
#  - "nginx"
#  - "php"
#  - "php-common"
#  - "php-cli"
#  - "php-fpm"
#  - "php-mysqlnd"
#  - "php-pdo"
#  - "php-mcrypt"  (N/A)
#  - "php-pecl-imagick" (N/A)

- name: Install Nginx and PHP for CentOS7 (Remi)
  when:
    - aws_awslinux=="no"
    - centos_phprepo=="remi"
  yum: name={{item}} state=latest
  with_items:
  - "nginx"
  - "{{php_version_yum}}"
  - "{{php_version_yum}}-php"
  - "{{php_version_yum}}-php-common"
  - "{{php_version_yum}}-php-cli"
  - "{{php_version_yum}}-php-fpm"
  - "{{php_version_yum}}-php-gd"
  - "{{php_version_yum}}-php-mbstring"
  - "{{php_version_yum}}-php-mysql"
  - "{{php_version_yum}}-php-opcache"
  - "{{php_version_yum}}-php-pdo"
  - "{{php_version_yum}}-php-xml"
  - "{{php_version_yum}}-php-gmp"
  - "{{php_version_yum}}-php-pecl-imagick"
  - "{{php_version_yum}}-php-pecl-zip"
  - "{{php_version_yum}}-php-pecl-redis"
  - "{{php_version_yum}}-php-pecl-memcached"
  - "jq"
- name: Install Nginx and PHP for CentOS7 (Remi)
  when:
    - aws_awslinux=="no"
    - centos_phprepo=="webtactics"
    - php_version_yum !="php72"
  yum: name={{item}} state=latest
  with_items:
   - "{{php_version_yum}}-php-mcrypt"

- name: Install Nginx and PHP for CentOS (Webtactics)
  when: aws_awslinux=="no"
  yum: name={{ item }} state=latest
  with_items:
  - "nginx"
  - "{{php_version_yum}}w"
  - "{{php_version_yum}}w-common"
  - "{{php_version_yum}}w-cli"
  - "{{php_version_yum}}w-devel"
  - "{{php_version_yum}}w-fpm"
  - "{{php_version_yum}}w-gd"
  - "{{php_version_yum}}w-intl"
  - "{{php_version_yum}}w-pdo"
  - "{{php_version_yum}}w-pecl-imagick"
  - "{{php_version_yum}}w-pecl-memcached"
  - "{{php_version_yum}}w-pecl-redis"
  - "{{php_version_yum}}w-mbstring"
  - "{{php_version_yum}}w-mysqlnd"
  - "{{php_version_yum}}w-opcache"
  - "{{php_version_yum}}w-soap"
  - "{{php_version_yum}}w-xml"
  - "jq"
- name: Install PHP mcrypt extention for CentOS7 (Webtactics)
  when:
    - aws_awslinux=="no"
    - centos_phprepo=="webtactics"
    - php_version_yum !="php72"
  yum: name={{item}} state=latest
  with_items:
  - "{{php_version_yum}}w-mcrypt"

- name: Add User to Nginx-group
  user: name={{ item }} groups=nginx state=present
  with_items: "{{ add_users }}"

- name: Add Nginx to User-group
  user: name=nginx groups={{ item }} state=present
  with_items: "{{ add_users }}"

- include: set_php-fpm.yml
  when:
  - centos_phprepo !="remi"
  - aws_awslinux !="1"
- include: set_php-fpm-al-1.yml
  when: aws_awslinux=="1"
- include: set_php-fpm-remi.yml
  when: centos_phprepo=="remi"
- include: set_php.yml
- include: set_nginx.yml
- include: set_nginx-vhost.yml

- name: Start Nginx
  when: centos_version=="6"
  service: name=nginx state=started enabled=yes
- name: Start php-fpm
  when: centos_version=="6"
  service: name=php-fpm state=started enabled=yes

- name: Start Nginx
  when: centos_version=="7"
  systemd: name=nginx state=started enabled=yes
- name: Start php-fpm
  when: centos_version=="7"
  systemd: name=php-fpm state=started enabled=yes
