- name: Install Nginx and PHP for Amazon Linux 1
  when: aws_awslinux=="1"
  yum: name={{ item }} state=latest
  with_items:
  - "nginx"
  - "{{php_version_yum}}"
  - "{{php_version_yum}}-common"
  - "{{php_version_yum}}-cli"
  - "{{php_version_yum}}-devel"
  - "{{php_version_yum}}-fpm"
  - "{{php_version_yum}}-gd"
  - "{{php_version_yum}}-intl"
  - "{{php_version_yum}}-mbstring"
  - "{{php_version_yum}}-mysqlnd"
  - "{{php_version_yum}}-opcache"
  - "{{php_version_yum}}-pdo"
  - "{{php_version_yum}}-pecl-memcached"
#  - "{{php_version_yum}}-pecl-redis" Not Available
  - "{{php_version_yum}}-xml"
  - "jq"
  register: NginxPHPResult
- name: Install PHP mcrypt extension for Amazon Linux
  when:
    - aws_awslinux=="1"
    - php_version_yum !="php72"
  yum: name={{item}} state=latest
  with_items:
  - "{{php_version_yum}}-mcrypt"

- name: Install Nginx and PHP for Amazon Linux 2
  when: aws_awslinux=="2"
  yum: name={{item}} state=latest enablerepo=amzn2extra-{{php_version_amznlinux2}}
  with_items:
  - "php"
  - "php-bcmath"
  - "php-cli"
  - "php-common"
  - "php-dba"
  - "php-embedded"
  - "php-enchant"
  - "php-fpm"
  - "php-gd"
  - "php-gmp"
  - "php-intl"
  - "php-json"
  - "php-ldap"
  - "php-mbstring"
  - "php-pecl-mcrypt"
  - "php-mysqlnd"
  - "php-odbc"
  - "php-opcache"
  - "php-pdo"
  - "php-pecl-igbinary"
  - "php-pecl-redis"
 # - "php-pecl-ssh2"
  - "php-pecl-zip"
  - "php-pgsql"
  - "php-process"
  - "php-pspell"
  - "php-recode"
  - "php-snmp"
  - "php-soap"
  - "php-xml"
  - "php-xmlrpc"
  register: NginxPHPResult

- name: Install Nginx and PHP for CentOS7 (Remi)
  when:
    - aws_awslinux=="no"
    - centos_phprepo=="remi"
  yum: name={{item}} state=latest enablerepo=epel,remi,remi-{{php_version_yum}}
  with_items:
  - "nginx"
  - "php"
  - "php-common"
  - "php-cli"
  - "php-fpm"
  - "php-gd"
  - "php-mbstring"
  - "php-mysql"
  - "php-opcache"
  - "php-pdo"
  - "php-xml"
  - "php-gmp"
  - "php-pecl-zip"
  - "php-pecl-redis"
  - "php-pecl-memcached"
  - "jq"
  register: NginxPHPResult
- name: Install Nginx and PHP for CentOS7 (Remi)
  when:
    - aws_awslinux=="no"
    - centos_phprepo=="remi"
    - php_version_yum !="php72"
  yum: name={{item}} state=latest enablerepo=epel,remi,remi-{{php_version_yum}}
  with_items:
   - "php-mcrypt"

- name: Install Nginx and PHP for CentOS (Webtactics)
  when: aws_awslinux=="no"
  yum: name={{ item }} state=latest
  with_items:
  - "nginx"
  - "{{php_version_yum}}w"
  - "{{php_version_yum}}w-common"
  - "{{php_version_yum}}w-cli"
  - "{{php_version_yum}}w-devel"
  - "{{php_version_yum}}w-fpm"
  - "{{php_version_yum}}w-gd"
  - "{{php_version_yum}}w-intl"
  - "{{php_version_yum}}w-pdo"
  - "{{php_version_yum}}w-pecl-memcached"
  - "{{php_version_yum}}w-pecl-redis"
  - "{{php_version_yum}}w-mbstring"
  - "{{php_version_yum}}w-mysqlnd"
  - "{{php_version_yum}}w-opcache"
  - "{{php_version_yum}}w-soap"
  - "{{php_version_yum}}w-xml"
  - "jq"
  register: NginxPHPResult
- name: Install PHP mcrypt extention for CentOS7 (Webtactics)
  when:
    - aws_awslinux=="no"
    - centos_phprepo=="webtactics"
    - php_version_yum !="php72"
  yum: name={{item}} state=latest
  with_items:
  - "{{php_version_yum}}w-mcrypt"

- name: Add User to Nginx-group
  user: name={{ item }} groups=nginx state=present
  with_items: "{{ add_users }}"

- name: Add Nginx to User-group
  user: name=nginx groups={{ item }} state=present
  with_items: "{{ add_users }}"

- name: Start Nginx
  when: centos_version=="6"
  service: name=nginx state=started enabled=yes
  when: NginxPHPResult.changed == True
- name: Start php-fpm
  when: centos_version=="6"
  service: name=php-fpm state=started enabled=yes
  when: NginxPHPResult.changed == True

- name: Start Nginx
  when: centos_version=="7"
  systemd: name=nginx state=started enabled=yes
  when: NginxPHPResult.changed == True
- name: Start php-fpm
  when: centos_version=="7"
  systemd: name=php-fpm state=started enabled=yes
  when: NginxPHPResult.changed == True

- include: set_php-fpm.yml
  when: aws_awslinux !="1"
- include: set_php-fpm-al-1.yml
  when: aws_awslinux=="1"

- include: set_php.yml

- include: set_nginx.yml
- include: set_nginx-vhost.yml

- name: Chenge Directory Permission -  Nginx Log
  file: path="/var/log/nginx/" state=directory recurse=yes mode=0755

- name: Chenge Directory Permission - PHP-fpm
  file: path="/var/log/php-fpm/" state=directory recurse=yes mode=0755
