# Amazon Linux 1
- name: Set PHP-FPM User to {{c5dir_user}}
  replace: >
    dest=/etc/php-fpm-{{php_version_amznlinux}}.d/www.conf
    regexp="user = apache"
    replace="user = {{c5dir_user}}"
  notify: Restart php-fpm
  when: webserver_changeowner=="yes"
- name: Set PHP-FPM User to nginx
  replace: >
    dest=/etc/php-fpm-{{php_version_amznlinux}}.d/www.conf
    regexp="user = apache"
    replace="user = nginx"
  notify: Restart php-fpm
  when: webserver_changeowner=="no"
- name: Set PHP-FPM Group to {{c5dir_group}}
  replace: >
    dest=/etc/php-fpm-{{php_version_amznlinux}}.d/www.conf
    regexp="group = apache"
    replace="group = {{c5dir_group}}"
  notify: Restart php-fpm
  when: webserver_changeowner=="yes"
- name: Set PHP-FPM Group to nginx
  replace: >
    dest=/etc/php-fpm-{{php_version_amznlinux}}.d/www.conf
    regexp="group = apache"
    replace="group = nginx"
  notify: Restart php-fpm
  when: webserver_changeowner=="no"
- name: Change PHP-FPM UnixSocket
  replace: >
    dest=/etc/php-fpm-{{php_version_amznlinux}}.d/www.conf
    regexp="listen = 127\.0\.0\.1:9000"
    replace="listen = {{ unixsocket_path }}"
  notify: Restart php-fpm
- name: Set PHP-FPM listen.owner to SSH user {{c5dir_user}}
  replace: >
    dest=/etc/php-fpm-{{php_version_amznlinux}}.d/www.conf
    regexp="^;listen\.owner = nobody"
    replace="listen.owner = {{c5dir_user}}"
  notify: Restart php-fpm
  when: webserver_changeowner=="yes"
- name: Set PHP-FPM listen.owner to nginx
  replace: >
    dest=/etc/php-fpm-{{php_version_amznlinux}}.d/www.conf
    regexp="^;listen\.owner = nobody"
    replace="listen.owner = nginx"
  notify: Restart php-fpm
  when: webserver_changeowner=="no"
- name: Set PHP-FPM listen.group to {{c5dir_group}}
  when: webserver_changeowner=="yes"
  replace: >
    dest=/etc/php-fpm-{{php_version_amznlinux}}.d/www.conf
    regexp="^;listen\.group = nobody"
    replace="listen.group = {{c5dir_group}}"
  notify: Restart php-fpm
- name: Set PHP-FPM listen.group to nginx
  when: webserver_changeowner=="no"
  replace: >
    dest=/etc/php-fpm-{{php_version_amznlinux}}.d/www.conf
    regexp="^;listen\.group = nobody"
    replace="listen.group = nginx"
  notify: Restart php-fpm
- name: Set PHP-FPM listen.acl_users
  replace: >
    dest=/etc/php-fpm-{{php_version_amznlinux}}.d/www.conf
    regexp="^listen.acl_users = apache,nginx"
    replace=";listen.acl_users = apache,nginx,{{c5dir_user}}"
  notify: Restart php-fpm
  when: webserver_changeowner=="yes"
- name: Change PHP-FPM mode from dynamic to static
  replace: >
    dest=/etc/php-fpm-{{php_version_amznlinux}}.d/www.conf
    regexp="pm = dynamic"
    replace="pm = static"
  notify: Restart php-fpm
- name: Set PHP-FPM listen.mode
  replace: >
    dest=/etc/php-fpm-{{php_version_amznlinux}}.d/www.conf
    regexp="^;listen\.mode = 0666"
    replace="listen.mode = 0660"
  notify: Restart php-fpm

# Amazon Linux 1 with PHP {{php_version_amznlinux}}
- name: Change Permission opcache dir
  file: path=/var/lib/php/{{php_version_amznlinux}}/opcache owner=root group={{c5dir_group}}
- name: Change Permission session dir
  file: path=/var/lib/php/{{php_version_amznlinux}}/session owner=root group={{c5dir_group}}
- name: Change Permission wsdlcache dir
  file: path=/var/lib/php/{{php_version_amznlinux}}/wsdlcache owner=root group={{c5dir_group}}
