- name: Install Mackerel agent for CentOS6
  when: centos_version=="6"
  shell: curl -fsSL https://mackerel.io/file/script/setup-all-yum.sh | MACKEREL_APIKEY='{{ mackerel_apikey }}' sh
- name: Install Mackerel agent for CentOS7
  when: centos_version=="7"
  shell: curl -fsSL https://mackerel.io/file/script/setup-all-yum-v2.sh | MACKEREL_APIKEY='{{ mackerel_apikey }}' sh