- name: Upload and unzip concrete5 Backup file
  unarchive: src="{{c5_backup_zip_filename}}.zip" dest="{{vhost_docroot}}{{vhost_domain}}"
  when: result.stat.exists == False
- name: Check if concrete5 files exist
  stat: path={{vhost_docroot}}{{vhost_domain}}/application/config/database.php
  register: concrete5copy
- name: Change concrete5 (webroot) permission
  file: path="{{vhost_docroot}}{{vhost_domain}}" state=directory recurse=yes owner={{c5dir_user}} group={{c5dir_group}} mode=0775
  when: concrete5copy.stat.exists == True
