- name: Check if concrete5 Installed
  stat: path={{vhost_docroot}}{{vhost_domain}}/application/config/database.php
  register: result

- include: 10_upload_concrete5_backup.yml
- include: 20_import_mysql.yml
- include: 30_upload_concrete5_config.yml
- include: 40_restart_nginx.yml
  when: webserver_handle=="nginx"
- include: 50_delete_backup.yml
