- name: Restart Nginx
  service: name=nginx state=restarted
  when:
    - centos_version=="6"
    - isDocker=="no"
  
- name: Restart Nginx
  systemd: name=nginx state=restarted
  when:
    - (centos_version=="7" or aws_awslinux=="2" or aws_awslinux=="2023")
    - isDocker=="no"