- name: Install MariaDB Server
  when: aws_awslinux!="2"
  yum:
    name:
      - MariaDB-server
    state: installed
  register: MariaDBServerResult

- name: Install MariaDB Server
  when:
    - aws_awslinux=="2"
    - mariadb_repo not in ["10.5"]
  yum:
    name:
      - mariadb-server
    state: installed
  register: MariaDBServerResult

- name: Install MariaDB Server
  when:
    - aws_awslinux=="2"
    - mariadb_repo=="10.5"
  yum:
    name:
      - mariadb-server
    state: installed
  register: MariaDBServerResult

# - name: Backup original /etc/my.cnf.d/server.cnf file
#   copy: src=/etc/my.cnf.d/server.cnf dest=/etc/my.cnf.d/server.cnf.bak mode=644
#   notify: Restart mysqld

- name: Replace MariaDB Config to support mb4
  template: src=server.cnf.j2 dest=/etc/my.cnf.d/server.cnf
  notify: Restart mysqld

- name: Start MariaDB (CentOS6)
  when:
    - centos_version=="6"
    - isDocker=="no"
  service: name=mysqld state=started enabled=yes
- name: Start MariaDB (CentOS7)
  when:
    - centos_version=="7"
    - isDocker=="no"
  systemd: name=mariadb state=started enabled=yes

- name: Set root Password
  mysql_user:
    name: "root"
    host: "{{ item }}"
    password: "{{ mysql_rootpass }}"
    state: present
  with_items:
    - 127.0.0.1
    - localhost
  # @ToDo: Somehow it s no longer detecting server change
  # when:
  #  - MariaDBServerResult.changed == True
 