- name: Install MariaDB Server
  when: aws_awslinux!="2"
  yum: name={{item}} state=installed
  with_items:
    - MariaDB-server
  register: MariaDBServerResult

- name: Install MariaDB Server
  when: aws_awslinux=="2"
  yum: name={{item}} state=installed
  with_items:
    - mariadb-server
  register: MariaDBServerResult

- name: Start mysqld (CentOS6)
  when: centos_version=="6"
  service: name=mysqld state=started enabled=yes
- name: Start mysqld (CentOS7)
  when: centos_version=="7"
  systemd: name=mysqld state=started enabled=yes

- name: Set root Password
  mysql_user: name="root" host={{ item }} password={{ mysql_rootpass }}
  with_items:
    - 127.0.0.1
    - localhost
  when: MariaDBServerResult.changed == True
