- name: Install MariaDB Server
  when: aws_awslinux!="2"
  yum: name={{item}} state=installed
  with_items:
    - MariaDB-server
  register: MariaDBServerResult

- name: Install MariaDB Server
  when: aws_awslinux=="2"
  yum: name={{item}} state=installed
  with_items:
    - mariadb-server
  register: MariaDBServerResult

- name: Backup original /etc/my.conf.d/server.cnf file
  copy: src=/etc/my.conf.d/server.cnf dest=/etc/my.conf.d/server.cnf.bak mode=0644 owner=root group=root
  notify: Restart mysqld

- name: Replace MySQL Config to support mb4
  template: src=server.cnf.j2 dest=/etc/my.conf.d/server.cnf
  notify: Restart mysqld

- name: Start mysqld (CentOS6)
  when: centos_version=="6"
  service: name=mysqld state=started enabled=yes
- name: Start mysqld (CentOS7)
  when: centos_version=="7"
  systemd: name=mariadb state=started enabled=yes

- name: Set root Password
  mysql_user: name="root" host={{ item }} password={{ mysql_rootpass }}
  with_items:
    - 127.0.0.1
    - localhost
  when: MariaDBServerResult.changed == True
  
  
