- name: Install MariaDB Server
  when: aws_awslinux!="2"
  yum:
    name:
      - MariaDB-server
    state: installed
  register: MariaDBServerResult

- name: Install MariaDB Server
  when:
    - aws_awslinux=="2"
    - mariadb_repo not in ["10.5","5.5"]
  yum:
    name:
      - mariadb-server
    state: installed
  register: MariaDBServerResult

- name: Install MariaDB Server
  when:
    - aws_awslinux=="2"
    - mariadb_repo in ["10.5","5.5"]
  yum:
    name:
      - mariadb-server
    state: installed
  register: MariaDBServerResult

# - name: Backup original /etc/my.cnf.d/server.cnf file
#   copy: src=/etc/my.cnf.d/server.cnf dest=/etc/my.cnf.d/server.cnf.bak mode=644
#   notify: Restart mysqld

- name: Replace MariaDB Config to support mb4
  template: src=server.cnf.j2 dest=/etc/my.cnf.d/server.cnf
  notify: Restart mysqld
  when:
  - mariadb_repo not in ["5.5"]

- name: Replace MariaDB Config to support mb4 only for MariaDB 5.5
  template: src=server5.5.cnf.j2 dest=/etc/my.cnf.d/server.cnf
  notify: Restart mysqld
  when:
  - mariadb_repo=="5.5"

- name: Start MariaDB (CentOS6)
  when:
    - centos_version=="6"
    - isDocker=="no"
  service: name=mysqld state=started enabled=yes
- name: Start MariaDB (CentOS7)
  when:
    - centos_version=="7"
    - isDocker=="no"
    - mariadb_repo not in ["5.5"]
  systemd: name=mariadb state=started enabled=yes
- name: Start MariaDB (CentOS7)
  when:
    - centos_version=="7"
    - isDocker=="no"
    - mariadb_repo in ["5.5"]
  systemd: name=mariadb state=started enabled=yes

- name: Set root Password
  mysql_user:
    login_unix_socket: /var/lib/mysql/mysql.sock
    login_user: 'root'
    login_password: ''
    name: 'root'
    password: '{{ mysql_rootpass }}'
    host_all: yes
    state: present
  when:
    - isDocker=="no"
