- name: Restart mysqld
  when:
    - centos_version=="6"
    - isDocker=="no"
  service: name=mysqld state=restarted
- name: Restart mysqld
  when:
    - centos_version=="7"
    - isDocker=="no"
  systemd: name=mysqld state=restarted
