- name: Remove MariaDB lib
  yum: name=mariadb-lib state=absent
  when: centos_version=="7"

- name: Install MySQL Repo for CentOS {{centos_version}}
  yum: name=http://dev.mysql.com/get/mysql-community-release-el{{centos_version}}-5.noarch.rpm state=present
  # As of Aug 2018, MySQL yum repo include MySQL 5.5.x through 5.7.x Experiment
