- name: Remove MariaDB lib (yum)
  yum:
    name:
      - mariadb-libs
    state: absent
  when: centos_version=="7" and aws_awslinux != "2023"

- name: Remove MariaDB lib (dnf for AL2023)
  dnf:
    name:
      - mariadb-libs
    state: absent
  when: aws_awslinux=="2023"

- name: Install MySQL Repo for CentOS/AL2 {{centos_version}}
  yum:
    name:
      - https://dev.mysql.com/get/mysql84-community-release-el{{centos_version}}-1.noarch.rpm
    state: present
  when: aws_awslinux != "2023"

- name: Install MySQL Repo for AL2023
  dnf:
    name:
      - https://dev.mysql.com/get/mysql84-community-release-el9-1.noarch.rpm
    state: present
  when: aws_awslinux == "2023"

- name: Disable MySQL8.4 Repo to Enable older version of MySQL (yum)
  command: yum-config-manager --disable mysql84-community
  when: mysql_repo not in ["80", "84"] and aws_awslinux != "2023"

- name: Disable MySQL8.4 Repo to Enable older version of MySQL (dnf)
  command: dnf config-manager --set-disabled mysql84-community
  when: mysql_repo not in ["80", "84"] and aws_awslinux == "2023"

- name: Enable older version of MySQL (yum)
  command: yum-config-manager --enable mysql{{mysql_repo}}-community
  when: mysql_repo not in ["80", "84"] and aws_awslinux != "2023"

- name: Enable older version of MySQL (dnf)
  command: dnf config-manager --set-enabled mysql{{mysql_repo}}-community
  when: mysql_repo not in ["80", "84"] and aws_awslinux == "2023"
