- name: Install Apache and PHP for Amazon Linux
  when: aws_awslinux=="1"
  yum: name={{item}} state=latest
  with_items:
  - "httpd24"
  - "{{php_version_yum}}"
  - "{{php_version_yum}}-common"
  - "{{php_version_yum}}-cli"
  - "{{php_version_yum}}-devel"
  - "{{php_version_yum}}-fpm"
  - "{{php_version_yum}}-gd"
  - "{{php_version_yum}}-intl"
  - "{{php_version_yum}}-mbstring"
  - "{{php_version_yum}}-mysqlnd"
  - "{{php_version_yum}}-opcache"
  - "{{php_version_yum}}-pdo"
  - "{{php_version_yum}}-pecl-memcached"
  - "{{php_version_yum}}-pecl-redis"
  - "{{php_version_yum}}-xml"
  - "jq"
- name: Install PHP mcrypt extension for Amazon Linux
  when:
    - aws_awslinux=="1"
    - php_version_yum !="php72"
  yum: name={{item}} state=latest
  with_items:
  - "{{php_version_yum}}-mcrypt"

- name: Install Amazon Linux Extra Lamp MariaDB for Amazon Linux 2
  shell: amazon-linux-extras install lamp-mariadb10.2-php7.2
  when: aws_awslinux=="2"

- name: Install Apache and PHP for Amazon Linux 2
  when: aws_awslinux=="2"
  yum: name={{item}} state=latest
  with_items:
  - "httpd"
  - "php-devel"
  - "php-gd"
  - "php-intl"
  - "php-mbstring"
  - "php-opcache"
#  - "php-pecl-memcache"
  - "php-xml"
#  - "php"
#  - "php-common"
#  - "php-cli"
#  - "php-fpm"
#  - "php-mysqlnd"
#  - "php-pdo"
#  - "php-mcrypt"  (N/A)

- name: Install Apache and PHP for CentOS7 (Remi)
  when:
    - aws_awslinux=="no"
    - centos_phprepo=="remi"
  yum: name={{item}} state=latest enablerepo=epel,remi,remi-{{php_version_yum}}
  with_items:
  - "httpd"
  - "php"
  - "php-common"
  - "php-devel"
  - "php-cli"
  - "php-fpm"
  - "php-gd"
  - "php-intl"
  - "php-mbstring"
  - "php-mysqlnd"
  - "php-opcache"
  - "php-pdo"
  - "php-gmp"
  - "php-pecl-memcached"
  - "php-pecl-redis"
  - "php-pecl-zip"
  - "php-xml"
  - "jq"
- name: Install PHP mcrypt extention for CentOS7 (Remi)
  when:
    - aws_awslinux=="no"
    - centos_phprepo=="remi"
    - php_version_yum !="php72"
  yum: name={{item}} state=latest
  with_items:
  - "php-mcrypt"

- name: Install Apache and PHP for CentOS7 (Webtactics)
  when:
    - aws_awslinux=="no"
    - centos_phprepo=="webtactics"
  yum: name={{item}} state=latest
  with_items:
  - "httpd"
  - "{{php_version_yum}}w"
  - "{{php_version_yum}}w-common"
  - "{{php_version_yum}}w-cli"
  - "{{php_version_yum}}w-devel"
  - "{{php_version_yum}}w-fpm"
  - "{{php_version_yum}}w-gd"
  - "{{php_version_yum}}w-intl"
  - "{{php_version_yum}}w-pdo"
  - "{{php_version_yum}}w-pecl-memcached"
  - "{{php_version_yum}}w-pecl-redis"
  - "{{php_version_yum}}w-mbstring"
  - "{{php_version_yum}}w-mcrypt"
  - "{{php_version_yum}}w-mysqlnd"
  - "{{php_version_yum}}w-opcache"
  - "{{php_version_yum}}w-soap"
  - "{{php_version_yum}}w-xml"
  - "jq"
- name: Install PHP mcrypt extention for CentOS7 (Webtactics)
  when:
    - aws_awslinux=="no"
    - centos_phprepo=="webtactics"
    - php_version_yum !="php72"
  yum: name={{item}} state=latest
  with_items:
  - "{{php_version_yum}}w-mcrypt"

- name: Add User to Apache-group
  user: name={{ item }} groups=apache state=present
  with_items: "{{ add_users }}"

- name: Add Apache to User-group
  user: name=apache groups={{ item }} state=present
  with_items: "{{ add_users }}"

- include: set_php-fpm.yml
  when: aws_awslinux !="1"
- include: set_php-fpm-al-1.yml
  when: aws_awslinux=="1"

- include: set_php.yml
  
- include: set_apache.yml
- include: set_apache-vhosts.yml
- include: set_htaccess.yml

- name: Start httpd
  when: centos_version=="6"
  service: name=httpd state=started enabled=yes
- name: Start php-fpm
  when: centos_version=="6"
  service: name=php-fpm state=started enabled=yes

- name: Start httpd
  when: centos_version=="7"
  systemd: name=httpd state=started enabled=yes
- name: Start php-fpm
  when: centos_version=="7"
  systemd: name=php-fpm state=started enabled=yes

- name: Chenge Directory Permission -  Apache Log
  file: path="/var/log/httpd/" state=directory recurse=yes mode=0755

- name: Chenge Directory Permission - PHP-fpm
  file: path="/var/log/php-fpm/" state=directory recurse=yes mode=0755
