- name: Install Apache for Amazon Linux
  when: aws_awslinux=="1"
  yum:
    name:
      - "httpd24"
    state: latest

- name: Install Apache for Amazon Linux 2
  when:
    - aws_awslinux!="1"
  yum:
    name:
      - "httpd"
    state: latest
    enablerepo: amzn2extra-{{php_version_amznlinux2}}
    disablerepo: epel

- name: Add User to Apache-group
  user: name={{ item }} groups=apache state=present
  with_items: "{{ add_users }}"

- name: Add Apache to User-group
  user: name=apache groups={{ item }} state=present
  with_items: "{{ add_users }}"

- include_tasks: set_apache.yml
- include_tasks: set_apache-vhosts.yml
- include_tasks: set_htaccess.yml

- name: Start httpd
  when:
    - centos_version=="6"
    - isDocker=="no"
  service: name=httpd state=started enabled=yes

- name: Start httpd
  when:
    - centos_version=="7"
    - isDocker=="no"
  systemd: name=httpd state=started enabled=yes

- name: Chenge Directory Permission -  Apache Log
  file: path="/var/log/httpd/" state=directory recurse=yes mode=0755
