- name: Install Apache for Amazon Linux
  when: aws_awslinux=="1"
  yum: name={{item}} state=latest
  with_items:
  - "httpd24"

- name: Install Apache for Amazon Linux 2
  when:
    - aws_awslinux!="1"
  yum: name={{item}} state=latest enablerepo=amzn2extra-{{php_version_amznlinux2}} disablerepo=epel
  with_items:
  - "httpd"

- name: Install Apache and PHP for Amazon Linux
  when: aws_awslinux=="1"
  yum: name={{item}} state=latest
  with_items:
  - "{{php_version_yum}}"
  - "{{php_version_yum}}-common"
  - "{{php_version_yum}}-cli"
  - "{{php_version_yum}}-devel"
  - "{{php_version_yum}}-fpm"
  - "{{php_version_yum}}-gd"
  - "{{php_version_yum}}-intl"
  - "{{php_version_yum}}-mbstring"
  - "{{php_version_yum}}-mysqlnd"
  - "{{php_version_yum}}-opcache"
  - "{{php_version_yum}}-pdo"
  - "{{php_version_yum}}-pecl-memcached"
#  - "{{php_version_yum}}-pecl-redis" # Not Available
  - "{{php_version_yum}}-xml"
  - "jq"
- name: Install PHP mcrypt extension for Amazon Linux
  when:
    - aws_awslinux=="1"
    - php_version_yum !="php72"
  yum: name={{item}} state=latest
  with_items:
  - "{{php_version_yum}}-mcrypt"

- name: Install Apache and PHP for Amazon Linux 2
  when:
    - aws_awslinux=="2"
    - php_version_amznlinux2!="php56"
  yum: name={{item}} state=latest enablerepo=amzn2extra-{{php_version_amznlinux2}} disablerepo=epel
  with_items:
  - "httpd"
  - "php"
  - "php-bcmath"
  - "php-cli"
  - "php-common"
  - "php-dba"
  - "php-embedded"
  - "php-enchant"
  - "php-fpm"
  - "php-gd"
  - "php-gmp"
  - "php-intl"
  - "php-json"
  - "php-ldap"
  - "php-mbstring"
 # - "php-pecl-mcrypt"
  - "php-mysqlnd"
  - "php-odbc"
  - "php-opcache"
  - "php-pdo"
  - "php-pecl-igbinary"
 # - "php-pecl-ssh2"
 # - "php-pecl-zip"
  - "php-pgsql"
  - "php-process"
  - "php-pspell"
 # - "php-recode"
  - "php-snmp"
  - "php-soap"
  - "php-xml"
  - "php-xmlrpc"
  register: NginxPHPResult

- name: Install PHP for Amazon Linux 2
  when:
    - aws_awslinux=="2"
    - php_version_amznlinux2 in ["php72", "php73"] 
  yum: name={{item}} state=latest enablerepo=amzn2extra-{{php_version_amznlinux2}} disablerepo=epel
  with_items:
  - "php-pecl-mcrypt"
  - "php-pecl-zip"

- name: Install PHP Redis Extension for Amazon Linux 2
  when:
    - aws_awslinux=="2"
    - php_version_yum not in ['php56', 'php70', 'php71']
  yum: name={{item}} state=latest enablerepo=amzn2extra-{{php_version_amznlinux2}} disablerepo=epel
  with_items:
  - "php-pecl-redis"


- name: Install Apache and PHP for CentOS6 & 7 (Remi)
  when:
    - aws_awslinux=="no"
    - centos_phprepo=="remi"
  yum: name={{item}} state=latest enablerepo=epel,remi,remi-{{php_version_yum}}
  with_items:
  - "php"
  - "php-common"
  - "php-devel"
  - "php-cli"
  - "php-fpm"
  - "php-gd"
  - "php-intl"
  - "php-mbstring"
  - "php-mysqlnd"
  - "php-opcache"
  - "php-pdo"
  - "php-gmp"
  - "php-pecl-memcached"
  - "php-pecl-redis"
  - "php-pecl-zip"
  - "php-xml"
- name: Install PHP mcrypt extention for CentOS7 (Remi)
  when:
    - aws_awslinux=="no"
    - centos_phprepo=="remi"
    - php_version_yum in ['php70', 'php71']
  yum: name={{item}} state=latest enablerepo=epel,remi,remi-{{php_version_yum}}
  with_items:
  - "php-mcrypt"

- name: Install Apache and PHP5.6 for Amazon Linux 2 Remi
  when:
    - aws_awslinux=="2"
    - php_version_amznlinux2=="php56"
  yum: name={{item}} state=latest enablerepo=epel,remi,remi-{{php_version_yum}}
  with_items:
  - "php"
  - "php-common"
  - "php-devel"
  - "php-cli"
  - "php-fpm"
  - "php-gd"
  - "php-intl"
  - "php-mbstring"
  - "php-mysqlnd"
  - "php-opcache"
  - "php-pdo"
  - "php-gmp"
  - "php-pecl-memcached"
  - "php-pecl-redis"
  - "php-pecl-zip"
  - "php-xml"
  - "php-mcrypt"

- name: Add User to Apache-group
  user: name={{ item }} groups=apache state=present
  with_items: "{{ add_users }}"

- name: Add Apache to User-group
  user: name=apache groups={{ item }} state=present
  with_items: "{{ add_users }}"

- include: set_php-fpm.yml
  when: aws_awslinux !="1"
- include: set_php-fpm-al-1.yml
  when: aws_awslinux=="1"

- include: set_php.yml
  
- include: set_apache.yml
- include: set_apache-vhosts.yml
- include: set_htaccess.yml

- name: Start httpd
  when: centos_version=="6"
  service: name=httpd state=started enabled=yes
- name: Start php-fpm
  when: centos_version=="6"
  service: name=php-fpm state=started enabled=yes

- name: Start httpd
  when: centos_version=="7"
  systemd: name=httpd state=started enabled=yes
- name: Start php-fpm
  when: centos_version=="7"
  systemd: name=php-fpm state=started enabled=yes

- name: Chenge Directory Permission -  Apache Log
  file: path="/var/log/httpd/" state=directory recurse=yes mode=0755

- name: Chenge Directory Permission - PHP-fpm
  file: path="/var/log/php-fpm/" state=directory recurse=yes mode=0755
