- name: Install Apache and PHP for Amazon Linux
  when: aws_awslinux=="1"
  yum: name={{item}} state=latest
  with_items:
  - "httpd24"
  - "php71"
  - "php71-common"
  - "php71-cli"
  - "php71-devel"
  - "php71-fpm"
  - "php71-gd"
  - "php71-intl"
  - "php71-mbstring"
  - "php71-mysqlnd"
  - "php71-mcrypt"
  - "php71-opcache"
  - "php71-pdo"
  - "php71-pecl-imagick"
  - "php71-pecl-memcached"
  - "php71-xml"
  - "jq"

- name: Install Amazon Linux Extra Lamp MariaDB for Amazon Linux 2
  shell: amazon-linux-extras install lamp-mariadb10.2-php7.2
  when: aws_awslinux=="2"

- name: Install Apache and PHP for Amazon Linux
  when: aws_awslinux=="2"
  yum: name={{item}} state=latest
  with_items:
  - "httpd"
  - "php-devel"
  - "php-gd"
  - "php-intl"
  - "php-mbstring"
  - "php-opcache"
#  - "php-pecl-memcache"
  - "php-xml"
#  - "php"
#  - "php-common"
#  - "php-cli"
#  - "php-fpm"
#  - "php-mysqlnd"
#  - "php-pdo"
#  - "php-mcrypt"  (N/A)
#  - "php-pecl-imagick" (N/A)

- name: Install Apache and PHP for CentOS7
  when: aws_awslinux=="no"
  yum: name={{item}} state=latest
  with_items:
  - "httpd"
  - "php71w"
  - "php71w-common"
  - "php71w-cli"
  - "php71w-devel"
  - "php71w-fpm"
  - "php71w-gd"
  - "php71w-intl"
  - "php71w-pdo"
  - "php71w-pecl-imagick"
  - "php71w-pecl-memcached"
  - "php71w-mbstring"
  - "php71w-mcrypt"
  - "php71w-mysqlnd"
  - "php71w-opcache"
  - "php71w-soap"
  - "php71w-xml"
  - "jq"

- name: Add User to Apache-group
  user: name={{ item }} groups=apache state=present
  with_items: "{{ add_users }}"

- name: Add Apache to User-group
  user: name=apache groups={{ item }} state=present
  with_items: "{{ add_users }}"

- include: set_php-fpm.yml
- include: set_php.yml
- include: set_apache.yml
- include: set_apache-vhosts.yml
- include: set_htaccess.yml

- name: Start httpd
  when: centos_version=="6"
  service: name=httpd state=started enabled=yes
- name: Start php-fpm
  when: centos_version=="6"
  service: name=php-fpm state=started enabled=yes

- name: Start httpd
  when: centos_version=="7"
  systemd: name=httpd state=started enabled=yes
- name: Start php-fpm
  when: centos_version=="7"
  systemd: name=php-fpm state=started enabled=yes
