# Amazon Linux 2 & CentOS
- name: Set PHP-FPM User
  replace: >
    dest=/etc/php-fpm.d/www.conf
    regexp="user = apache"
    replace="user = {{webserver_user}}"
  notify: Restart php-fpm
  when: webserver_changeowner=="yes"
- name: Set PHP-FPM Group
  replace: >
    dest=/etc/php-fpm.d/www.conf
    regexp="group = apache"
    replace="group = {{webserver_group}}"
  notify: Restart php-fpm
  when: webserver_changeowner=="yes"
- name: Change PHP-FPM UnixSocket
  replace: >
    dest=/etc/php-fpm.d/www.conf
    regexp="listen = 127\.0\.0\.1:9000"
    replace="listen = {{ unixsocket_path }}"
  notify: Restart php-fpm
- name: Set PHP-FPM listen.owner to SSH user
  replace: >
    dest=/etc/php-fpm.d/www.conf
    regexp="^;listen\.owner = nobody"
    replace="listen.owner = {{webserver_user}}"
  notify: Restart php-fpm
  when: webserver_changeowner=="yes"
- name: Set PHP-FPM listen.owner to apache
  when: webserver_changeowner=="no"
  replace: >
    dest=/etc/php-fpm.d/www.conf
    regexp="^;listen\.owner = nobody"
    replace="listen.owner = apache"
  notify: Restart php-fpm
- name: Set PHP-FPM listen.group
  replace: >
    dest=/etc/php-fpm.d/www.conf
    regexp="^;listen\.group = nobody"
    replace="listen.group = {{webserver_group}}"
  notify: Restart php-fpm
- name: Set PHP-FPM listen.acl_users
  replace: >
    dest=/etc/php-fpm.d/www.conf
    regexp="^listen.acl_users = apache,nginx"
    replace=";listen.acl_users = apache,nginx,{{c5dir_user}}"
  notify: Restart php-fpm
  when: webserver_changeowner=="yes"
- name: Change PHP-FPM mode from dynamic to static
  replace: >
    dest=/etc/php-fpm.d/www.conf
    regexp="pm = dynamic"
    replace="pm = static"
  notify: Restart php-fpm
- name: Set PHP-FPM listen.mode
  replace: >
    dest=/etc/php-fpm.d/www.conf
    regexp="^;listen\.mode = 0666"
    replace="listen.mode = 0660"
  notify: Restart php-fpm

# CentOS7 with webtactics repo & Amazon Linux 2
- name: Change Permission session_dir
  file: path=/var/lib/php/session owner=root group={{webserver_group}}
- name: Change Permission wsdlcache_dir
  file: path=/var/lib/php/wsdlcache owner=root group={{webserver_group}}

- name: Check if php.conf exist
  stat: path=/etc/httpd/conf.d/php.conf
  register: phpconffile
- name: Disable Apache php setting
  command: mv /etc/httpd/conf.d/php.conf /etc/httpd/conf.d/php.conf.bak
  when: phpconffile.stat.exists == True
  notify: Restart Apache
