# Amazon Linux 2 & CentOS
- name: Set php-fpm config
  template: src=www.conf.{{aws_instance_type}}.j2 dest=/etc/php-fpm.d/www.conf
  notify: Restart php-fpm

# CentOS7 with webtactics repo & Amazon Linux 2
- name: Change Permission opcache dir
  file: path=/var/lib/php/opcache owner=root group={{c5dir_group}}
- name: Change Permission session dir
  file: path=/var/lib/php/session owner=root group={{c5dir_group}}
- name: Change Permission wsdlcache dir
  file: path=/var/lib/php/wsdlcache owner=root group={{c5dir_group}}
