- name: Set PHP TimeZone
  replace: >
    dest=/etc/php.ini
    regexp="^;date\.timezone ="
    replace="date.timezone = Asia/Tokyo"
  notify: Restart php-fpm
- name: Enable PHP short_open_tag
  replace: >
    dest=/etc/php.ini
    regexp="short_open_tag = Off"
    replace="short_open_tag = On"
  notify: Restart php-fpm
- name: Disabled PHP expose_php
  replace: >
    dest=/etc/php.ini
    regexp="expose_php = On"
    replace="expose_php = Off"
  notify: Restart php-fpm
- name: Change PHP max_execution_time
  replace: >
    dest=/etc/php.ini
    regexp="max_execution_time = 60"
    replace="max_execution_time = {{php_max_execution_time}}"
  notify: Restart php-fpm
- name: Change PHP max_input_time
  replace: >
    dest=/etc/php.ini
    regexp="max_input_time = 60"
    replace="max_input_time = {{php_max_input_time}}"
  notify: Restart php-fpm
- name: Change PHP max_input_vars
  replace: >
    dest=/etc/php.ini
    regexp="^; max_input_vars = 1000"
    replace="max_input_vars = {{php_max_input_vars}}"
  when: php_max_input_vars not in ['1000'] 
  notify: Restart php-fpm
- name: Change PHP memory_limit
  replace: >
    dest=/etc/php.ini
    regexp="memory_limit = 128M"
    replace="memory_limit = {{php_memory_limit}}"
  notify: Restart php-fpm
- name: Set PHP error log
  replace: >
    dest=/etc/php.ini
    regexp=";error_log = php_errors.log"
    replace="error_log = {{php_path_error_log}}"
  notify: Restart php-fpm
- name: Change PHP post_max_size
  replace: >
    dest=/etc/php.ini
    regexp="post_max_size = 8M"
    replace="post_max_size = {{php_post_max_size}}"
  notify: Restart php-fpm
- name: Change PHP upload_max_filesize
  replace: >
    dest=/etc/php.ini
    regexp="upload_max_filesize = 2M"
    replace="upload_max_filesize = {{php_upload_max_filesize}}"
  notify: Restart php-fpm
