- name: Install mysql
  yum: name={{item}} state=latest
  with_items:
  - "mysql56"
  - mysql56-common
  - mysql56-devel
  - mysql56-libs
  register: result
- name: Install pip
  when: aws_awslinux=="no"
  yum: name=python-pip state=latest
