- name: Install mysql
  yum: name={{item}} state=latest
  when: aws_awslinux =="1"
  with_items:
  - mysql56
  - mysql56-common
  - mysql56-devel
  - mysql56-libs
  register: result

- name: Install mysql
  yum: name={{item}} state=latest
  when: aws_awslinux =="no"
  with_items:
  - mysql-community-client
  - mysql-community-common
  - mysql-community-devel
  - mysql-community-libs
  register: result

- name: Install pip
  when: aws_awslinux=="no"
  yum: name=python-pip state=latest
- name: Install python mysqlmodule
  when: aws_awslinux not in ["2"]
  pip: name=mysql state=latest
