- name: Install MySQL Client for Amazon Linux 1
  yum: name={{item}} state=latest
  when: aws_awslinux =="1"
  with_items:
  - mysql{{mysql_repo}}
  - mysql{{mysql_repo}}-common
  - mysql{{mysql_repo}}-devel
  - mysql{{mysql_repo}}-libs
  register: result

- name: Install MySQL Client
  yum: name={{item}} state=latest
  when: aws_awslinux =="no"
  with_items:
  - mysql-community-client
  - mysql-community-common
  - mysql-community-devel
  - mysql-community-libs
  register: result

- name: Install pip
  when: aws_awslinux=="no"
  yum: name=python-pip state=latest
  
- name: Install Python MySQLModule
  when: aws_awslinux not in ["2"]
  pip: name=mysql state=latest
