- name: Install mysql
  yum: name={{item}} state=latest
  with_items:
  - "mysql56"
  - mysql56-common
  - mysql56-devel
  - mysql56-libs
  register: result
- name: Install pip
  when: aws_awslinux!="yes"
  yum: name=python-pip state=latest
- name: Install python mysqlmodule
  pip: name=mysql state=latest
