- name: Restart Apache
  when:
    - centos_version=="6"
    - isDocker=="no"
  service: name=httpd state=restarted enabled=yes
- name: Restart php-fpm
  when:
    - centos_version=="6"
    - isDocker=="no"
  service: name=php-fpm state=restarted
- name: Restart Apache
  when:
    - centos_version=="7"
    - isDocker=="no"
  systemd: name=httpd state=restarted enabled=yes
- name: Restart php-fpm
  when:
    - centos_version=="7"
    - isDocker=="no"
  systemd: name=php-fpm state=restarted
