- name: Restart Apache
  when:
    - centos_version=="6"
    - isDocker=="no"
  service: name=httpd state=restarted enabled=yes
- name: Restart Apache
  when:
    - centos_version=="7"
    - isDocker=="no"
  systemd: name=httpd state=restarted enabled=yes
